# 4.8 Grouping data & aggregating variables

### This script contains:

#### 1. Import libraries
#### 2. Import data
#### 3. Find the aggregated mean of the order_number column grouped by department_id
#### 4. Create a loyalty flag for existing customers
#### 5. Spending habits of customers
#### 6. Low and high spenders
#### 7. Frequent and non-frequent customers
#### 8. Exporting final dataframe

# Import libraries

In [1]:
# import libraries

import pandas as pd
import numpy as np
import os

# Import data

In [2]:
# project folder path

path = r'C:\Users\Odette\Desktop\CareerFoundry\Immersion Courses\Course 4\Instacart Basket Analysis'

In [3]:
# import of orders_products_merged data

ords_prods_merge = pd.read_pickle(os.path.join(path, '02 Data','Prepared Data', 'orders_products1.pkl'))

In [4]:
ords_prods_merge.head()

,Unnamed: 0,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_last_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,price_range_loc,busiest_days,busiest_period_of_day
0,0,2539329,1,1,2,8,0.0,196,1,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Average orders
1,1,2398795,1,2,3,7,15.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Average orders
2,2,473747,1,3,3,12,21.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Most orders
3,3,2254736,1,4,4,7,29.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Average orders
4,4,431534,1,5,4,15,28.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Most orders

# Find the aggregated mean of the order_number column grouped by department_id

In [5]:
# obtain the mean values for the “order_number” column (with agg function)

ords_prods_merge.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
1                15.457838
2                17.277920
3                17.170395
4                17.811403
5                15.215751
6                16.439806
7                17.225802
8                15.340650
9                15.895474
10               20.197148
11               16.170638
12               15.887671
13               16.583536
14               16.773669
15               16.165037
16               17.665606
17               15.694469
18               19.310397
19               17.177343
20               16.473447
21               22.902379

This aggregation includes all 21 department id's, whereas the subset only contained 8 department id's. It includes all information, not just a sample

# Create a loyalty flag for existing customers

In [6]:
# creating a flag for customers with many orders

ords_prods_merge['max_order'] = ords_prods_merge.groupby(['user_id'])['order_number'].transform(np.max)

In [7]:
ords_prods_merge.head()

,Unnamed: 0,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_last_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,price_range_loc,busiest_days,busiest_period_of_day,max_order
0,0,2539329,1,1,2,8,0.0,196,1,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Average orders,10
1,1,2398795,1,2,3,7,15.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Average orders,10
2,2,473747,1,3,3,12,21.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Most orders,10
3,3,2254736,1,4,4,7,29.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Average orders,10
4,4,431534,1,5,4,15,28.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Most orders,10

In [8]:
# create flag for loyal customers (max_order over 40)

ords_prods_merge.loc[ords_prods_merge['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'

In [9]:
# create flag for regular customers (max_order between 10 & 40)

ords_prods_merge.loc[(ords_prods_merge['max_order'] <= 40) & (ords_prods_merge['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'

In [10]:
# create flag for loyal customers (max_order under 10)

ords_prods_merge.loc[ords_prods_merge['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [11]:
ords_prods_merge['loyalty_flag'].value_counts(dropna = False)

Regular customer    15876776
Loyal customer      10284093
New customer         6243990
Name: loyalty_flag, dtype: int64

In [12]:
# head results just for user_id, loyalty_flag & order_number

ords_prods_merge[['user_id', 'loyalty_flag', 'order_number']].head(20)

    user_id      loyalty_flag  order_number
0         1      New customer             1
1         1      New customer             2
2         1      New customer             3
3         1      New customer             4
4         1      New customer             5
5         1      New customer             6
6         1      New customer             7
7         1      New customer             8
8         1      New customer             9
9         1      New customer            10
10       15  Regular customer            15
11       15  Regular customer            17
12       15  Regular customer            18
13       15  Regular customer            21
14       15  Regular customer            22
15       19      New customer             2
16       19      New customer             5
17       19      New customer             7
18       21  Regular customer            10
19       31  Regular customer            10
20       31  Regular customer            17
21       43  Regular customer             6
22       43  Regular customer             9
23       52  Regular customer             1
24       52  Regular customer             2
25       52  Regular customer             3
26       52  Regular customer             5
27       52  Regular customer             7
28       52  Regular customer             9
29       52  Regular customer            10
30       52  Regular customer            11
31       52  Regular customer            12
32       52  Regular customer            15
33       52  Regular customer            17
34       52  Regular customer            18
35       52  Regular customer            19
36       52  Regular customer            21
37       67  Regular customer             1
38       67  Regular customer             2
39       67  Regular customer             3
40       67  Regular customer             4
41       67  Regular customer             5
42       67  Regular customer             6
43       67  Regular customer             8
44       67  Regular customer             9
45       67  Regular customer            10
46       67  Regular customer            11
47       67  Regular customer            12
48       67  Regular customer            13
49       67  Regular customer            14
50       67  Regular customer            16
51       67  Regular customer            18
52       67  Regular customer            19
53       67  Regular customer            21
54       67  Regular customer            22
55       67  Regular customer            23
56       81      New customer             3
57       81      New customer             5
58       82  Regular customer             1
59       82  Regular customer             3

# Spending habits of customers

In [13]:
# group by loyalty_flag to determine stats on price differences in the groups

ords_prods_merge.groupby('loyalty_flag').agg({'prices': ['mean', 'min', 'max']})

                     prices
                       mean  min      max
loyalty_flag
Loyal customer    10.386336  1.0  99999.0
New customer      13.294670  1.0  99999.0
Regular customer  12.495717  1.0  99999.0

# Low and high spenders

In [14]:
# creating a flag for customers' average spend

ords_prods_merge['average_spend'] = ords_prods_merge.groupby(['user_id'])['prices'].transform(np.mean)

In [15]:
ords_prods_merge.head()

,Unnamed: 0,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_last_order,product_id,add_to_cart_order,reordered,...,aisle_id,department_id,prices,_merge,price_range_loc,busiest_days,busiest_period_of_day,max_order,loyalty_flag,average_spend
0,0,2539329,1,1,2,8,0.0,196,1,0,...,77,7,9.0,both,Mid-range product,Regularly busy,Average orders,10,New customer,6.367797
1,1,2398795,1,2,3,7,15.0,196,1,1,...,77,7,9.0,both,Mid-range product,Least busy,Average orders,10,New customer,6.367797
2,2,473747,1,3,3,12,21.0,196,1,1,...,77,7,9.0,both,Mid-range product,Least busy,Most orders,10,New customer,6.367797
3,3,2254736,1,4,4,7,29.0,196,1,1,...,77,7,9.0,both,Mid-range product,Least busy,Average orders,10,New customer,6.367797
4,4,431534,1,5,4,15,28.0,196,1,1,...,77,7,9.0,both,Mid-range product,Least busy,Most orders,10,New customer,6.367797

In [16]:
# create flag for high spenders (average_spend 10 or over)

ords_prods_merge.loc[ords_prods_merge['average_spend'] >= 10, 'spending_type'] = 'High spender'

In [17]:
# create flag for low spenders (average_spend under 10)

ords_prods_merge.loc[ords_prods_merge['average_spend'] < 10, 'spending_type'] = 'Low spender'

In [18]:
pd.options.display.max_rows = None

In [19]:
ords_prods_merge.head(100)

,Unnamed: 0,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_last_order,product_id,add_to_cart_order,reordered,...,department_id,prices,_merge,price_range_loc,busiest_days,busiest_period_of_day,max_order,loyalty_flag,average_spend,spending_type
0,0,2539329,1,1,2,8,0.0,196,1,0,...,7,9.0,both,Mid-range product,Regularly busy,Average orders,10,New customer,6.367797,Low spender
1,1,2398795,1,2,3,7,15.0,196,1,1,...,7,9.0,both,Mid-range product,Least busy,Average orders,10,New customer,6.367797,Low spender
2,2,473747,1,3,3,12,21.0,196,1,1,...,7,9.0,both,Mid-range product,Least busy,Most orders,10,New customer,6.367797,Low spender
3,3,2254736,1,4,4,7,29.0,196,1,1,...,7,9.0,both,Mid-range product,Least busy,Average orders,10,New customer,6.367797,Low spender
4,4,431534,1,5,4,15,28.0,196,1,1,...,7,9.0,both,Mid-range product,Least busy,Most orders,10,New customer,6.367797,Low spender
5,5,3367565,1,6,2,7,19.0,196,1,1,...,7,9.0,both,Mid-range product,Regularly busy,Average orders,10,New customer,6.367797,Low spender
6,6,550135,1,7,1,9,20.0,196,1,1,...,7,9.0,both,Mid-range product,Busiest days,Most orders,10,New customer,6.367797,Low spender
7,7,3108588,1,8,1,14,14.0,196,2,1,...,7,9.0,both,Mid-range product,Busiest days,Most orders,10,New customer,6.367797,Low spender
8,8,2295261,1,9,1,16,0.0,196,4,1,...,7,9.0,both,Mid-range product,Busiest days,Most orders,10,New customer,6.367797,Low spender
9,9,2550362,1,10,4,8,30.0,196,1,1,...,7,9.0,both,Mid-range product,Least busy,Average orders,10,New customer,6.367797,Low spender
10,144,2968173,15,15,1,9,7.0,196,2,0,...,7,9.0,both,Mid-range product,Busiest days,Most orders,22,Regular customer,3.980556,Low spender
11,146,1870022,15,17,2,16,8.0,196,6,1,...,7,9.0,both,Mid-range product,Regularly busy,Most orders,22,Regular customer,3.980556,Low spender
12,147,1911383,15,18,2,11,7.0,196,1,1,...,7,9.0,both,Mid-range product,Regularly busy,Most orders,22,Regular customer,3.980556,Low spender
13,150,2715276,15,21,1,9,7.0,196,1,1,...,7,9.0,both,Mid-range product,Busiest days,Most orders,22,Regular customer,3.980556,Low spender
14,151,487368,15,22,1,10,14.0,196,1,1,...,7,9.0,both,Mid-range product,Busiest days,Most orders,22,Regular customer,3.980556,Low spender
15,209,2293453,19,2,5,14,6.0,196,3,0,...,7,9.0,both,Mid-range product,Regularly busy,Most orders,9,New customer,8.372059,Low spender
16,212,1973799,19,5,6,12,8.0,196,15,1,...,7,9.0,both,Mid-range product,Regularly busy,Most orders,9,New customer,8.372059,Low spender
17,214,532817,19,7,4,17,6.0,196,1,1,...,7,9.0,both,Mid-range product,Least busy,Most orders,9,New customer,8.372059,Low spender
18,232,1573906,21,10,3,10,6.0,196,2,0,...,7,9.0,both,Mid-range product,Least busy,Most orders,33,Regular customer,7.012683,Low spender
19,458,1593000,31,10,3,8,7.0,196,17,0,...,7,9.0,both,Mid-range product,Least busy,Average orders,20,Regular customer,8.137793,Low spender
20,465,2231262,31,17,3,11,8.0,196,14,1,...,7,9.0,both,Mid-range product,Least busy,Most orders,20,Regular customer,8.137793,Low spender
21,617,2580647,43,6,4,16,4.0,196,9,0,...,7,9.0,both,Mid-range product,Least busy,Most orders,11,Regular customer,7.444898,Low spender
22,620,2187180,43,9,4,12,3.0,196,1,1,...,7,9.0,both,Mid-range product,Least busy,Most orders,11,Regular customer,7.444898,Low spender
23,751,2497897,52,1,1,9,0.0,196,4,0,...,7,9.0,both,Mid-range product,Busiest days,Most orders,27,Regular customer,6.356287,Low spender
24,752,1318871,52,2,1,10,7.0,196,5,1,...,7,9.0,both,Mid-range product,Busiest days,Most orders,27,Regular customer,6.356287,Low spender
25,753,1261384,52,3,1,10,7.0,196,3,1,...,7,9.0,both,Mid-range product,Busiest days,Most orders,27,Regular customer,6.356287,Low spender
26,755,580568,52,5,2,10,8.0,196,6,1,...,7,9.0,both,Mid-range product,Regularly busy,Most orders,27,Regular customer,6.356287,Low spender
27,757,2428073,52,7,2,7,8.0,196,5,1,...,7,9.0,both,Mid-range product,Regularly busy,Average orders,27,Regular customer,6.356287,Low spender
28,759,342306,52,9,1,11,7.0,196,5,1,...,7,9.0,both,Mid-range product,Busiest days,Most orders,27,Regular customer,6.356287,Low spender
29,760,1520353,52,10,2,10,8.0,196,4,1,...,7,9.0,both,Mid-range product,Regularly busy,Most orders,27,Regular customer,6.356287,Low spender
30,761,2542086,52,11,2,9,7.0,196,3,1,...,7,9.0,both,Mid-range product,Regularly busy,Most orders,27,Regular customer,6.356287,Low spender
31,762,944694,52,12,1,16,6.0,196,7,1,...,7,9.0,both,Mid-range product,Busiest days,Most orders,27,Regular customer,6.356287,Low spender
32,765,1268191,52,15,2,11,8.0,196,3,1,...,7,9.0,both,Mid-range product,Regularly busy,Most orders,27,Regular customer,6.356287,Low spender
33,767,1122089,52,17,2,10,6.0,196,4,1,...,7,9.0,both,Mid-range product,Regularly busy,Most orders,27,Regular customer,6.356287,Low spender
34,768,1498922,52,18,2,10,14.0,196,6,1,...,7,9.0,both,Mid-range product,Regularly busy,Most orders,27,Regular customer,6.356287,Low spender
35,769,180919,52,19,3,8,8.0,196,4,1,...,7,9.0,both,Mid-range product,Least busy,Average orders,27,Regular customer,6.356287,Low spender
36,771,2695875,52,21,5,10,30.0,196,1,1,...,7,9.0,both,Mid-range product,Regularly busy,Most orders,27,Regular customer,6.356287,Low spender
37,1022,3205960,67,1,3,11,0.0,196,1,0,...,7,9.0,both,Mid-range product,Least busy,Most orders,24,Regular customer,7.656790,Low spender
38,1023,970922,67,2,1,15,5.0,196,2,1,...,7,9.0,both,Mid-range product,Busiest days,Most orders,24,Regular customer,7.656790,Low spender
39,1024,596585,67,3,1,13,7.0,196,2,1,...,7,9.0,both,Mid-range product,Busiest days,Most orders,24,Regular customer,7.656790,Low spender
40,1025,2037087,67,4,2,9,8.0,196,1,1,...,7,9.0,both,Mid-range product,Regularly busy,Most orders,24,Regular customer,7.656790,Low spender
41,1026,2474111,67,5,3,14,8.0,196,2,1,...,7,9.0,both,Mid-range product,Least busy,Most orders,24,Regular customer,7.656790,Low spender
42,1027,1568481,67,6,3,12,7.0,196,2,1,...,7,9.0,both,Mid-range product,Least busy,Most orders,24,Regular customer,7.656790,Low spender
43,1029,2048527,67,8,2,11,7.0,196,1,1,...,7,9.0,both,Mid-range product,Regularly busy,Most orders,24,Regular customer,7.656790,Low spender
44,1030,2389031,67,9,2,14,7.0,196,1,1,...,7,9.0,both,Mid-range product,Regularly busy,Most orders,24,Regular customer,7.656790,Low spender
45,1031,2378562,67,10,1,10,6.0,196,1,1,...,7,9.0,both,Mid-range product,Busiest days,Most orders,24,Regular customer,7.656790,Low spender
46,1032,1515698,67,11,1,11,7.0,196,1,1,...,7,9.0,both,Mid-range product,Busiest days,Most orders,24,Regular customer,7.656790,Low spender
47,1033,1928050,67,12,2,12,8.0,196,1,1,...,7,9.0,both,Mid-range product,Regularly busy,Most orders,24,Regular customer,7.656790,Low spender
48,1034,1949274,67,13,1,10,6.0,196,1,1,...,7,9.0,both,Mid-range product,Busiest days,Most orders,24,Regular customer,7.656790,Low spender
49,1035,551869,67,14,1,9,7.0,196,1,1,...,7,9.0,both,Mid-range product,Busiest days,Most orders,24,Regular customer,7.656790,Low spender
50,1037,768572,67,16,4,10,9.0,196,1,1,...,7,9.0,both,Mid-range product,Least busy,Most orders,24,Regular customer,7.656790,Low spender
51,1039,150528,67,18,5,16,4.0,196,1,1,...,7,9.0,both,Mid-range product,Regularly busy,Most orders,24,Regular customer,7.656790,Low spender
52,1040,29758,67,19,0,14,9.0,196,2,1,...,7,9.0,both,Mid-range product,Busiest days,Most orders,24,Regular customer,7.656790,Low spender
53,1042,1558976,67,21,1,9,5.0,196,2,1,...,7,9.0,both,Mid-range product,Busiest days,Most orders,24,Regular customer,7.656790,Low spender
54,1043,863974,67,22,1,11,14.0,196,3,1,...,7,9.0,both,Mid-range product,Busiest days,Most orders,24,Regular customer,7.656790,Low spender
55,1044,2308399,67,23,1,14,14.0,196,1,1,...,7,9.0,both,Mid-range product,Busiest days,Most orders,24,Regular customer,7.656790,Low spender
56,1202,2759128,81,3,1,9,14.0,196,2,0,...,7,9.0,both,Mid-range product,Busiest days,Most orders,7,New customer,8.165385,Low spender
57,1204,1812985,81,5,2,20,30.0,196,1,1,...,7,9.0,both,Mid-range product,Regularly busy,Average orders,7,New customer,8.165385,Low spender
58,1208,1889835,82,1,3,15,0.0,196,6,0,...,7,9.0,both,Mid-range product,Least busy,Most orders,19,Regular customer,6.441221,Low spender
59,1210,499460,82,3,5,10,5.0,196,2,1,...,7,9.0,both,Mid-range product,Regularly busy,Most orders,19,Regular customer,6.441221,Low spender
60,1211,2728456,82,4,0,11,16.0,196,1,1,...,7,9.0,both,Mid-range product,Busiest days,Most orders,19,Regular customer,6.441221,Low spender
61,1213,2653743,82,6,4,9,13.0,196,5,1,...,7,9.0,both,Mid-range product,Least busy,Most orders,19,Regular customer,6.441221,Low spender
62,1216,1358880,82,9,1,10,30.0,196,1,1,...,7,9.0,both,Mid-range product,Busiest days,Most orders,19,Regular customer,6.441221,Low spender
63,1217,343588,82,10,2,11,1.0,196,1,1,...,7,9.0,both,Mid-range product,Regularly busy,Most orders,19,Regular customer,6.441221,Low spender
64,1222,3034663,82,15,2,11,12.0,196,1,1,...,7,9.0,both,Mid-range product,Regularly busy,Most orders,19,Regular customer,6.441221,Low spender
65,1225,147262,82,18,1,13,7.0,196,1,1,...,7,9.0,both,Mid-range product,Busiest days,Most orders,19,Regular customer,6.441221,Low spender
66,1226,3144004,82,19,2,15,8.0,196,1,1,...,7,9.0,both,Mid-range product,Regularly busy,Most orders,19,Regular customer,6.441221,Low spender
67,1480,2126069,98,3,0,9,25.0,196,7,0,...,7,9.0,both,Mid-range product,Busiest days,Most orders,14,Regular customer,8.028000,Low spender
68,1484,2210120,98,7,5,14,5.0,196,1,1,...,7,9.0,both,Mid-range product,Regularly busy,Most orders,14,Regular customer,8.028000,Low spender
69,1486,681011,98,9,3,9,30.0,196,1,1,...,7,9.0,both,Mid-range product,Least busy,Most orders,14,Regular customer,8.028000,Low spender
70,1488,2846344,98,11,4,13,15.0,196,2,1,...,7,9.0,both,Mid-range product,Least busy,Most orders,14,Regular customer,8.028000,Low spender
71,1489,747431,98,12,6,13,30.0,196,4,1,...,7,9.0,both,Mid-range product,Regularly busy,Most orders,14,Regular customer,8.028000,Low spender
72,1490,2383054,98,13,4,11,30.0,196,1,1,...,7,9.0,both,Mid-range product,Least busy,Most orders,14,Regular customer,8.028000,Low spender
73,1491,1993729,98,14,5,8,8.0,196,2,1,...,7,9.0,both,Mid-range product,Regularly busy,Average orders,14,Regular customer,8.028000,Low spender
74,1608,1403849,109,3,3,17,9.0,196,5,0,...,7,9.0,both,Mid-range product,Least busy,Most orders,6,New customer,5.850725,Low spender
75,1744,520620,120,1,3,11,0.0,196,2,0,...,7,9.0,both,Mid-range product,Least busy,Most orders,3,New customer,9.385714,Low spender
76,1746,3273029,120,3,2,8,19.0,196,2,1,...,7,9.0,both,Mid-range product,Regularly busy,Average orders,3,New customer,9.385714,Low spender
77,2781,1861943,185,2,1,12,25.0,196,10,0,...,7,9.0,both,Mid-range product,Busiest days,Most orders,6,New customer,7.715000,Low spender
78,2891,2040988,195,1,1,14,0.0,196,2,0,...,7,9.0,both,Mid-range product,Busiest days,Most orders,58,Loyal customer,7.149730,Low spender
79,2898,1680569,195,8,1,9,4.0,196,2,1,...,7,9.0,both,Mid-range product,Busiest days,Most orders,58,Loyal customer,7.149730,Low spender
80,2909,276171,195,19,5,11,3.0,196,2,1,...,7,9.0,both,Mid-range product,Regularly busy,Most orders,58,Loyal customer,7.149730,Low spender
81,2912,2744976,195,22,5,10,7.0,196,2,1,...,7,9.0,both,Mid-range product,Regularly busy,Most orders,58,Loyal customer,7.149730,Low spender
82,2915,2781919,195,25,1,14,4.0,196,1,1,...,7,9.0,both,Mid-range product,Busiest days,Most orders,58,Loyal customer,7.149730,Low spender
83,2921,1738718,195,31,2,8,4.0,196,2,1,...,7,9.0,both,Mid-range product,Regularly busy,Average orders,58,Loyal customer,7.149730,Low spender
84,2924,3058369,195,34,3,10,6.0,196,2,1,...,7,9.0,both,Mid-range product,Least busy,Most orders,58,Loyal customer,7.149730,Low spender
85,2927,1485596,195,37,2,15,0.0,196,2,1,...,7,9.0,both,Mid-range product,Regularly busy,Most orders,58,Loyal customer,7.149730,Low spender
86,2930,417035,195,40,3,16,2.0,196,2,1,...,7,9.0,both,Mid-range product,Least busy,Most orders,58,Loyal customer,7.149730,Low spender
87,2937,1615297,195,47,5,10,2.0,196,2,1,...,7,9.0,both,Mid-range product,Regularly busy,Most orders,58,Loyal customer,7.149730,Low spender
88,2942,1765587,195,52,3,12,2.0,196,3,1,...,7,9.0,both,Mid-range product,Least busy,Most orders,58,Loyal customer,7.149730,Low spender
89,2947,745908,195,57,4,11,3.0,196,3,1,...,7,9.0,both,Mid-range product,Least busy,Most orders,58,Loyal customer,7.149730,Low spender
90,3451,2505656,222,17,2,12,1.0,196,2,0,...,7,9.0,both,Mid-range product,Regularly busy,Most orders,70,Loyal customer,6.862397,Low spender
91,3472,3268370,222,38,5,15,1.0,196,6,1,...,7,9.0,both,Mid-range product,Regularly busy,Most orders,70,Loyal customer,6.862397,Low spender
92,4667,2016711,290,9,5,19,6.0,196,8,0,...,7,9.0,both,Mid-range product,Regularly busy,Average orders,51,Loyal customer,7.285597,Low spender
93,4686,2706088,290,28,6,10,7.0,196,16,1,...,7,9.0,both,Mid-range product,Regularly busy,Most orders,51,Loyal customer,7.285597,Low spender
94,5551,1952286,331,6,5,16,30.0,196,8,0,...,7,9.0,both,Mid-range product,Regularly busy,Most orders,8,New customer,7.705128,Low spender
95,5895,3226575,360,1,5,12,0.0,196,1,0,...,7,9.0,both,Mid-range product,Regularly busy,Most orders,3,New customer,10.006250,High spender
96,6137,1469869,377,3,5,17,3.0,196,9,0,...,7,9.0,both,Mid-range product,Regularly busy,Most orders,3,New customer,8.496552,Low spender
97,6259,1927023,387,2,4,10,22.0,196,3,0,...,7,9.0,both,Mid-range product,Least busy,Most orders,8,New customer,7.396610,Low spender
98,6740,858092,420,4,1,19,30.0,196,2,0,...,7,9.0,both,Mid-range product,Busiest days,Average orders,22,Regular customer,7.387805,Low spender
99,6741,119314,420,5,3,19,16.0,196,2,1,...,7,9.0,both,Mid-range product,Least busy,Average orders,22,Regular customer,7.387805,Low spender

# Frequent and non-frequent customers

In [20]:
# create a flag for customers order frequency based on median of days_since_prior_order 

ords_prods_merge['median_order_days'] = ords_prods_merge.groupby(['user_id'])['days_since_last_order'].transform(np.median)

In [21]:
ords_prods_merge.head(15)

,Unnamed: 0,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_last_order,product_id,add_to_cart_order,reordered,...,prices,_merge,price_range_loc,busiest_days,busiest_period_of_day,max_order,loyalty_flag,average_spend,spending_type,median_order_days
0,0,2539329,1,1,2,8,0.0,196,1,0,...,9.0,both,Mid-range product,Regularly busy,Average orders,10,New customer,6.367797,Low spender,20.0
1,1,2398795,1,2,3,7,15.0,196,1,1,...,9.0,both,Mid-range product,Least busy,Average orders,10,New customer,6.367797,Low spender,20.0
2,2,473747,1,3,3,12,21.0,196,1,1,...,9.0,both,Mid-range product,Least busy,Most orders,10,New customer,6.367797,Low spender,20.0
3,3,2254736,1,4,4,7,29.0,196,1,1,...,9.0,both,Mid-range product,Least busy,Average orders,10,New customer,6.367797,Low spender,20.0
4,4,431534,1,5,4,15,28.0,196,1,1,...,9.0,both,Mid-range product,Least busy,Most orders,10,New customer,6.367797,Low spender,20.0
5,5,3367565,1,6,2,7,19.0,196,1,1,...,9.0,both,Mid-range product,Regularly busy,Average orders,10,New customer,6.367797,Low spender,20.0
6,6,550135,1,7,1,9,20.0,196,1,1,...,9.0,both,Mid-range product,Busiest days,Most orders,10,New customer,6.367797,Low spender,20.0
7,7,3108588,1,8,1,14,14.0,196,2,1,...,9.0,both,Mid-range product,Busiest days,Most orders,10,New customer,6.367797,Low spender,20.0
8,8,2295261,1,9,1,16,0.0,196,4,1,...,9.0,both,Mid-range product,Busiest days,Most orders,10,New customer,6.367797,Low spender,20.0
9,9,2550362,1,10,4,8,30.0,196,1,1,...,9.0,both,Mid-range product,Least busy,Average orders,10,New customer,6.367797,Low spender,20.0
10,144,2968173,15,15,1,9,7.0,196,2,0,...,9.0,both,Mid-range product,Busiest days,Most orders,22,Regular customer,3.980556,Low spender,8.0
11,146,1870022,15,17,2,16,8.0,196,6,1,...,9.0,both,Mid-range product,Regularly busy,Most orders,22,Regular customer,3.980556,Low spender,8.0
12,147,1911383,15,18,2,11,7.0,196,1,1,...,9.0,both,Mid-range product,Regularly busy,Most orders,22,Regular customer,3.980556,Low spender,8.0
13,150,2715276,15,21,1,9,7.0,196,1,1,...,9.0,both,Mid-range product,Busiest days,Most orders,22,Regular customer,3.980556,Low spender,8.0
14,151,487368,15,22,1,10,14.0,196,1,1,...,9.0,both,Mid-range product,Busiest days,Most orders,22,Regular customer,3.980556,Low spender,8.0

In [22]:
# create flag for non-frequent customers (order_frequency over 20)

ords_prods_merge.loc[ords_prods_merge['median_order_days'] > 20, 'order_frequency'] = 'Non-frequent customer'

In [23]:
# create flag for regular customers (order_frequency between 10 & 20)

ords_prods_merge.loc[(ords_prods_merge['median_order_days'] > 10) & (ords_prods_merge['median_order_days'] <= 20), 'order_frequency'] = 'Regular customer'

In [24]:
# create flag for frequent customers (order_frequency under 10)

ords_prods_merge.loc[ords_prods_merge['median_order_days'] <= 10, 'order_frequency'] = 'Frequent customer'

In [25]:
ords_prods_merge.head(20)

,Unnamed: 0,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_last_order,product_id,add_to_cart_order,reordered,...,_merge,price_range_loc,busiest_days,busiest_period_of_day,max_order,loyalty_flag,average_spend,spending_type,median_order_days,order_frequency
0,0,2539329,1,1,2,8,0.0,196,1,0,...,both,Mid-range product,Regularly busy,Average orders,10,New customer,6.367797,Low spender,20.0,Regular customer
1,1,2398795,1,2,3,7,15.0,196,1,1,...,both,Mid-range product,Least busy,Average orders,10,New customer,6.367797,Low spender,20.0,Regular customer
2,2,473747,1,3,3,12,21.0,196,1,1,...,both,Mid-range product,Least busy,Most orders,10,New customer,6.367797,Low spender,20.0,Regular customer
3,3,2254736,1,4,4,7,29.0,196,1,1,...,both,Mid-range product,Least busy,Average orders,10,New customer,6.367797,Low spender,20.0,Regular customer
4,4,431534,1,5,4,15,28.0,196,1,1,...,both,Mid-range product,Least busy,Most orders,10,New customer,6.367797,Low spender,20.0,Regular customer
5,5,3367565,1,6,2,7,19.0,196,1,1,...,both,Mid-range product,Regularly busy,Average orders,10,New customer,6.367797,Low spender,20.0,Regular customer
6,6,550135,1,7,1,9,20.0,196,1,1,...,both,Mid-range product,Busiest days,Most orders,10,New customer,6.367797,Low spender,20.0,Regular customer
7,7,3108588,1,8,1,14,14.0,196,2,1,...,both,Mid-range product,Busiest days,Most orders,10,New customer,6.367797,Low spender,20.0,Regular customer
8,8,2295261,1,9,1,16,0.0,196,4,1,...,both,Mid-range product,Busiest days,Most orders,10,New customer,6.367797,Low spender,20.0,Regular customer
9,9,2550362,1,10,4,8,30.0,196,1,1,...,both,Mid-range product,Least busy,Average orders,10,New customer,6.367797,Low spender,20.0,Regular customer
10,144,2968173,15,15,1,9,7.0,196,2,0,...,both,Mid-range product,Busiest days,Most orders,22,Regular customer,3.980556,Low spender,8.0,Frequent customer
11,146,1870022,15,17,2,16,8.0,196,6,1,...,both,Mid-range product,Regularly busy,Most orders,22,Regular customer,3.980556,Low spender,8.0,Frequent customer
12,147,1911383,15,18,2,11,7.0,196,1,1,...,both,Mid-range product,Regularly busy,Most orders,22,Regular customer,3.980556,Low spender,8.0,Frequent customer
13,150,2715276,15,21,1,9,7.0,196,1,1,...,both,Mid-range product,Busiest days,Most orders,22,Regular customer,3.980556,Low spender,8.0,Frequent customer
14,151,487368,15,22,1,10,14.0,196,1,1,...,both,Mid-range product,Busiest days,Most orders,22,Regular customer,3.980556,Low spender,8.0,Frequent customer
15,209,2293453,19,2,5,14,6.0,196,3,0,...,both,Mid-range product,Regularly busy,Most orders,9,New customer,8.372059,Low spender,6.0,Frequent customer
16,212,1973799,19,5,6,12,8.0,196,15,1,...,both,Mid-range product,Regularly busy,Most orders,9,New customer,8.372059,Low spender,6.0,Frequent customer
17,214,532817,19,7,4,17,6.0,196,1,1,...,both,Mid-range product,Least busy,Most orders,9,New customer,8.372059,Low spender,6.0,Frequent customer
18,232,1573906,21,10,3,10,6.0,196,2,0,...,both,Mid-range product,Least busy,Most orders,33,Regular customer,7.012683,Low spender,7.0,Frequent customer
19,458,1593000,31,10,3,8,7.0,196,17,0,...,both,Mid-range product,Least busy,Average orders,20,Regular customer,8.137793,Low spender,6.0,Frequent customer
20,465,2231262,31,17,3,11,8.0,196,14,1,...,both,Mid-range product,Least busy,Most orders,20,Regular customer,8.137793,Low spender,6.0,Frequent customer
21,617,2580647,43,6,4,16,4.0,196,9,0,...,both,Mid-range product,Least busy,Most orders,11,Regular customer,7.444898,Low spender,10.0,Frequent customer
22,620,2187180,43,9,4,12,3.0,196,1,1,...,both,Mid-range product,Least busy,Most orders,11,Regular customer,7.444898,Low spender,10.0,Frequent customer
23,751,2497897,52,1,1,9,0.0,196,4,0,...,both,Mid-range product,Busiest days,Most orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer
24,752,1318871,52,2,1,10,7.0,196,5,1,...,both,Mid-range product,Busiest days,Most orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer
25,753,1261384,52,3,1,10,7.0,196,3,1,...,both,Mid-range product,Busiest days,Most orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer
26,755,580568,52,5,2,10,8.0,196,6,1,...,both,Mid-range product,Regularly busy,Most orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer
27,757,2428073,52,7,2,7,8.0,196,5,1,...,both,Mid-range product,Regularly busy,Average orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer
28,759,342306,52,9,1,11,7.0,196,5,1,...,both,Mid-range product,Busiest days,Most orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer
29,760,1520353,52,10,2,10,8.0,196,4,1,...,both,Mid-range product,Regularly busy,Most orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer
30,761,2542086,52,11,2,9,7.0,196,3,1,...,both,Mid-range product,Regularly busy,Most orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer
31,762,944694,52,12,1,16,6.0,196,7,1,...,both,Mid-range product,Busiest days,Most orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer
32,765,1268191,52,15,2,11,8.0,196,3,1,...,both,Mid-range product,Regularly busy,Most orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer
33,767,1122089,52,17,2,10,6.0,196,4,1,...,both,Mid-range product,Regularly busy,Most orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer
34,768,1498922,52,18,2,10,14.0,196,6,1,...,both,Mid-range product,Regularly busy,Most orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer
35,769,180919,52,19,3,8,8.0,196,4,1,...,both,Mid-range product,Least busy,Average orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer
36,771,2695875,52,21,5,10,30.0,196,1,1,...,both,Mid-range product,Regularly busy,Most orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer
37,1022,3205960,67,1,3,11,0.0,196,1,0,...,both,Mid-range product,Least busy,Most orders,24,Regular customer,7.656790,Low spender,7.0,Frequent customer
38,1023,970922,67,2,1,15,5.0,196,2,1,...,both,Mid-range product,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0,Frequent customer
39,1024,596585,67,3,1,13,7.0,196,2,1,...,both,Mid-range product,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0,Frequent customer
40,1025,2037087,67,4,2,9,8.0,196,1,1,...,both,Mid-range product,Regularly busy,Most orders,24,Regular customer,7.656790,Low spender,7.0,Frequent customer
41,1026,2474111,67,5,3,14,8.0,196,2,1,...,both,Mid-range product,Least busy,Most orders,24,Regular customer,7.656790,Low spender,7.0,Frequent customer
42,1027,1568481,67,6,3,12,7.0,196,2,1,...,both,Mid-range product,Least busy,Most orders,24,Regular customer,7.656790,Low spender,7.0,Frequent customer
43,1029,2048527,67,8,2,11,7.0,196,1,1,...,both,Mid-range product,Regularly busy,Most orders,24,Regular customer,7.656790,Low spender,7.0,Frequent customer
44,1030,2389031,67,9,2,14,7.0,196,1,1,...,both,Mid-range product,Regularly busy,Most orders,24,Regular customer,7.656790,Low spender,7.0,Frequent customer
45,1031,2378562,67,10,1,10,6.0,196,1,1,...,both,Mid-range product,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0,Frequent customer
46,1032,1515698,67,11,1,11,7.0,196,1,1,...,both,Mid-range product,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0,Frequent customer
47,1033,1928050,67,12,2,12,8.0,196,1,1,...,both,Mid-range product,Regularly busy,Most orders,24,Regular customer,7.656790,Low spender,7.0,Frequent customer
48,1034,1949274,67,13,1,10,6.0,196,1,1,...,both,Mid-range product,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0,Frequent customer
49,1035,551869,67,14,1,9,7.0,196,1,1,...,both,Mid-range product,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0,Frequent customer
50,1037,768572,67,16,4,10,9.0,196,1,1,...,both,Mid-range product,Least busy,Most orders,24,Regular customer,7.656790,Low spender,7.0,Frequent customer
51,1039,150528,67,18,5,16,4.0,196,1,1,...,both,Mid-range product,Regularly busy,Most orders,24,Regular customer,7.656790,Low spender,7.0,Frequent customer
52,1040,29758,67,19,0,14,9.0,196,2,1,...,both,Mid-range product,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0,Frequent customer
53,1042,1558976,67,21,1,9,5.0,196,2,1,...,both,Mid-range product,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0,Frequent customer
54,1043,863974,67,22,1,11,14.0,196,3,1,...,both,Mid-range product,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0,Frequent customer
55,1044,2308399,67,23,1,14,14.0,196,1,1,...,both,Mid-range product,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0,Frequent customer
56,1202,2759128,81,3,1,9,14.0,196,2,0,...,both,Mid-range product,Busiest days,Most orders,7,New customer,8.165385,Low spender,30.0,Non-frequent customer
57,1204,1812985,81,5,2,20,30.0,196,1,1,...,both,Mid-range product,Regularly busy,Average orders,7,New customer,8.165385,Low spender,30.0,Non-frequent customer
58,1208,1889835,82,1,3,15,0.0,196,6,0,...,both,Mid-range product,Least busy,Most orders,19,Regular customer,6.441221,Low spender,11.0,Regular customer
59,1210,499460,82,3,5,10,5.0,196,2,1,...,both,Mid-range product,Regularly busy,Most orders,19,Regular customer,6.441221,Low spender,11.0,Regular customer

# Exporting final dataframe

In [26]:
# export data to pkl

ords_prods_merge.to_pickle(os.path.join(path, '02 Data','Prepared Data', 'orders_products.pkl'))